"""empty message

Revision ID: c42dd8acf471
Revises: 48b6e4fa82a1
Create Date: 2018-12-22 10:53:18.264000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c42dd8acf471'
down_revision = '48b6e4fa82a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('record_income_expenditure',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ctime', sa.DateTime(), nullable=True),
    sa.Column('utime', sa.DateTime(), nullable=True),
    sa.Column('creator_id', sa.Integer(), nullable=True),
    sa.Column('creator', sa.String(length=64), nullable=True),
    sa.Column('record_content', sa.Text(length=2000), nullable=True),
    sa.Column('remark', sa.Text(length=2000), nullable=True),
    sa.Column('entry_account_status', sa.Integer(), nullable=True),
    sa.Column('entry_account_time', sa.DateTime(), nullable=True),
    sa.Column('reviewer_id', sa.String(length=64), nullable=True),
    sa.Column('reviewer', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_record_income_expenditure_creator'), 'record_income_expenditure', ['creator'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_record_income_expenditure_creator'), table_name='record_income_expenditure')
    op.drop_table('record_income_expenditure')
    # ### end Alembic commands ###
